package chap15_exception;

public class _02_TryCatchFilnally {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] intArr = new int[3];
		
		int idx = 0;
		
		while(true) {
			try {
				System.out.println(intArr[idx]);
			} catch(Exception e) {
				//예외 메시지 출력
				System.out.println(e.getMessage());
			}
		}
	}

}
