package chap15_exception;

import java.util.Scanner;

public class _05_GenerateException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc = new Scanner(System.in);
		
		System.out.println("아이디를 입력하세요.");
		String id = sc.nextLine();
		System.out.println("비밀번호를 입력하세요.");
		String pw = sc.nextLine();
		
		try {
			checkUserId(id, pw);
		} catch(RuntimeException re) {
			if(re.getMessage().equals("idNotExist")) {
				System.out.println("에러코드: 201");
				System.out.println("아이디가 존재하지 않습니다.");
			} else if(re.getMessage().equals("wrongPassword")) {
				System.out.println("에러코드: 202");
				System.out.println("비밀번호가 일치하지 않습니다.");
			}
		}
		
		sc.close();
	}
	
	public static void checkUserId(String userId, String userPw) {
		String dbUserId = "aaa";
		String dbUserPw = "1111";
		
		if(!userId.equals(dbUserId)) {
			// 예외발생시키기
			// () 안의 내용이 메시지
			throw new RuntimeException("idNotExist");
		}
		
		if(!userPw.equals(dbUserPw)) {
			throw new RuntimeException("wrongPassword");
		}
		
		System.out.println(userId + "님 환영합니다.");
	}

}
