package chap15_exception;

public class _02_TryCatchFilnally {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] intArr = new int[3];
		
		int idx = 0;
		
		while(true) {
			try {
				System.out.println(intArr[idx]);
			} catch(ArrayIndexOutOfBoundsException ae) {
				//예외 메시지 출력
				System.out.println(ae.getMessage());
				System.out.println("인덱스의 범위를 초과했습니다.");
				System.out.println("프로그램을 종료합니다.");
				break;
			}
		}
	}

}
